owner: baealex
repo: upptime
user-agent: blex-bot

sites:
  - name: BLEX - https://blex.me
    url: https://blex.me/robots.txt
  - name: API - https://api.blex.me
    url: https://api.blex.me/robots.txt
  - name: STATIC - https://static.blex.me
    url: http://static.blex.me/robots.txt

status-website:
  cname: status.blex.me
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for BLEX"
  introMessage: BLEX의 상태입니다. [Upptime](https://github.com/upptime/upptime)에서 만들고 [GitHub](https://github.com)에서 운영합니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - baealex

notifications:
  - type: discord
